###
POST http://prism-demo.test:8080/prism/openai/v1/chat/completions
Content-Type: application/json

{
  "model": "spatula-creator",
  "messages": [
    {"role": "user", "content": "Hello, who are you?"}
  ]
}

###
GET http://localhost/prism/openai/v1/models

###
POST http://prism-demo.test:8080/prism/openai/v1/chat/completions
Content-Type: application/json

{
    "model": "spatula-creator",
    "messages": [
        {"role": "user", "content": "Hello, who are you?"}
    ]
}

###
GET http://prism-demo.test:8080/prism/openai/v1/models

###


